version: '3'
services:
  php:
    image: tompouce/php7.2-fpm-alpine-symfony:0.4
    volumes:
      - ../app:/home/www/symfonyproject
      - ~/.gitconfig:/root/.gitconfig
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./dockerlive/logs:/var/log
    working_dir: /home/www/
    environment:
      - PHP_IDE_CONFIG=serverName=symfonyproject_server
    tty: true
    links:
      - db
  nginx:
    image: tompouce/nginx-1.17.5-alpine:0.1
    ports:
      - '80:80'
    links:
      - php
      - db
    volumes:
      - ../app:/home/www/symfonyproject
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./dockerlive/logs:/var/log/nginx
  db:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=tompouce
      - MYSQL_PASSWORD=tompouce