version: '3'
services:
  php:
    image: tompouce/php:7.2-apache-symfony
    ports:
      - "8000:8000"
    volumes:
      - ../app:/home/www/symfony_test
      - ../app_demo:/home/www/my-project-name
      - ~/.gitconfig:/root/.gitconfig
    working_dir: /home/www/
    tty: true
  nginx-server:
    image: tompouce/nginx-alpine:1.17.5
    ports:
      - "8888:80"
    links:
      - php
    volumes:
      - ../app:/home/www/symfony_test
      - ../app_demo:/home/www/my-project-name
      - ./nginx/conf.d/:/etc/nginx/conf.d/